// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {stylesage} from '../models';

export function FetchFabricResult(arg1:string):Promise<string>;

export function ProcessStyleSage(arg1:stylesage.Request):Promise<string>;

export function ReadClipboard():Promise<string>;

export function SearchDictionary(arg1:string):Promise<{[key: string]: string}>;
