// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FetchFabricResult(arg1:string):Promise<string>;

export function ReadClipboard():Promise<string>;

export function SearchDictionary(arg1:string):Promise<{[key: string]: string}>;
