// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FetchFabricResult(arg1) {
  return window['go']['main']['App']['FetchFabricResult'](arg1);
}

export function ReadClipboard() {
  return window['go']['main']['App']['ReadClipboard']();
}

export function SearchDictionary(arg1) {
  return window['go']['main']['App']['SearchDictionary'](arg1);
}
